services:
  connection.factory.credis:
    class: Vainyl\CRedis\Factory\CRedisConnectionFactory
    arguments: ['@redis.script.storage']
  database.factory.credis:
    class: Vainyl\CRedis\Factory\CRedisDatabaseFactory
    arguments: ['@connection.storage']
  cache.factory.credis: '@database.factory.credis'